guest_list=["busra","tanu","sompa","anika"]
print(guest_list)
message=(f"{guest_list[1]} is not comming for dinner")
print(message)
del guest_list[1]
print(guest_list)
guest_list.insert( 1, "nupur")
print(guest_list)
message=(f"{guest_list[0]}  please join us for dinner")
print(message)
message=(f"{guest_list[1]}  please join us for dinner")
print(message)
message=(f"{guest_list[2]}  please join us for dinner")
print(message)
message=(f"{guest_list[3]}  please join us for dinner")
print(message)
inform=("we found a bigger dinner table so we want to more guest")
print(inform)
guest_list.insert(0, "tina")
message=(f"{guest_list[0]} please join us for dinner")
print(message)
guest_list.insert(2, "bristy")
message=(f"{guest_list[2]} please join us for dinner")
print(message)
guest_list.append("borsha")
message=(f"{guest_list[-1]} please join us for dinner")
print(message)

